package dev.th7bo.sidequest.protocol

import kotlinx.serialization.Serializable

/**
 * The wire contract, versioned.
 *
 * One number for the whole protocol rather than one per endpoint. A friend group runs one server and
 * a handful of clients that update at different times, so what matters is "can these two talk", and
 * per-endpoint versioning answers a question nobody is asking while making every request carry a
 * negotiation.
 */
public object Protocol {

    /**
     * What this build speaks.
     *
     * Bumped when a change would break the other side. Adding an optional field does not break
     * anything — `ignoreUnknownKeys` and default values handle it — so most changes are not a bump.
     * Removing a field, renaming one, or changing what a value means is.
     */
    public const val VERSION: Int = 1

    /**
     * The oldest version this build will talk to.
     *
     * Kept as a separate number so the server can accept a client one version behind while the group
     * updates, rather than everybody having to update in the same evening. When it equals [VERSION],
     * only exact matches are accepted.
     */
    public const val MINIMUM_VERSION: Int = 1

    /** Header carrying the caller's protocol version on every HTTP request. */
    public const val VERSION_HEADER: String = "X-Sidequest-Protocol"

    /**
     * Header carrying a caller-generated request id.
     *
     * Generated by the client, echoed by the server, and logged on both sides — which is what makes
     * "my ping did not arrive" answerable. Without it the only way to correlate the two logs is by
     * timestamp, and the two clocks disagree.
     */
    public const val REQUEST_ID_HEADER: String = "X-Sidequest-Request-Id"

    /** Header carrying the server's clock, so the client can measure the offset. See [ServerTime]. */
    public const val SERVER_TIME_HEADER: String = "X-Sidequest-Server-Time"

    /** Whether [version] is one this build can talk to. */
    public fun isCompatible(version: Int): Boolean = version in MINIMUM_VERSION..VERSION
}

/**
 * The result of asking the server what it speaks.
 *
 * Fetched once at startup, before anything else. A client that discovers the mismatch on its first
 * real request has already queued writes it cannot send, and unpicking that is worse than refusing to
 * connect.
 */
@Serializable
public data class ServerInfo(
    public val protocolVersion: Int,
    public val minimumProtocolVersion: Int,
    /** For a human reading a log or a diagnostics screen. */
    public val serverVersion: String,
    /** The server's clock in epoch milliseconds, for [ServerTime]. */
    public val timeMillis: Long,
    /** Whether this server is accepting new device pairings at all. */
    public val pairingEnabled: Boolean = true,
) {

    /** Whether a client speaking [Protocol.VERSION] can talk to this server. */
    public val isCompatibleWithThisBuild: Boolean
        get() = Protocol.VERSION in minimumProtocolVersion..protocolVersion &&
            protocolVersion >= Protocol.MINIMUM_VERSION
}

/**
 * The offset between our clock and the server's.
 *
 * Needed because every timestamp that crosses the wire is compared against something. A ready check
 * that expires in thirty seconds, an event that is too stale to replay, a debt created "before" a
 * payment — all of them are wrong if the two machines disagree about the time, and machines disagree
 * about the time constantly.
 *
 * Held as an offset rather than by rewriting timestamps: the local clock is what the local UI shows,
 * and the offset is applied only where a comparison crosses the boundary.
 */
@Serializable
public data class ServerTime(
    /** Add this to a local timestamp to get the server's idea of it. */
    public val offsetMillis: Long = 0,
    /** Round-trip time of the measurement, in milliseconds. The offset is no better than this. */
    public val roundTripMillis: Long = 0,
) {

    public fun toServer(localMillis: Long): Long = localMillis + offsetMillis

    public fun toLocal(serverMillis: Long): Long = serverMillis - offsetMillis

    /**
     * Whether the offset is worth trusting.
     *
     * A measurement taken over a slow round trip is mostly noise. Beyond this the offset is kept for
     * diagnostics and not applied, because a bad correction is worse than none.
     */
    public val isUsable: Boolean get() = roundTripMillis in 0..MAX_USABLE_ROUND_TRIP_MILLIS

    public companion object {
        public val None: ServerTime = ServerTime()

        public const val MAX_USABLE_ROUND_TRIP_MILLIS: Long = 2_000

        /**
         * Estimates the offset from one request.
         *
         * The standard NTP-style estimate: assume the server's timestamp was taken halfway through the
         * round trip. Crude, and accurate to within the round trip, which is all anything here needs.
         */
        public fun estimate(sentAtMillis: Long, serverMillis: Long, receivedAtMillis: Long): ServerTime {
            val roundTrip = receivedAtMillis - sentAtMillis
            val midpoint = sentAtMillis + roundTrip / 2
            return ServerTime(offsetMillis = serverMillis - midpoint, roundTripMillis = roundTrip)
        }
    }
}

/** Every HTTP path the protocol defines, in one place so neither side can typo one. */
public object Endpoints {

    public const val BASE: String = "/api"

    /** Unauthenticated. What the server speaks, and its clock. */
    public const val SERVER_INFO: String = "$BASE/info"

    // -- pairing (unauthenticated) ------------------------------------------

    /** Starts a pairing. Returns a code to show the user and a secret to poll with. */
    public const val PAIR_START: String = "$BASE/pair/start"

    /** Polls a pairing. Authenticated by the device secret, not by a token. */
    public const val PAIR_POLL: String = "$BASE/pair/poll"

    /** Approves a pairing. Called by an already-authenticated operator, never by the mod. */
    public const val PAIR_APPROVE: String = "$BASE/pair/approve"

    // -- session ------------------------------------------------------------

    /** Exchanges a refresh token for a new access token. */
    public const val TOKEN_REFRESH: String = "$BASE/session/refresh"

    /** Revokes this device. */
    public const val SESSION_REVOKE: String = "$BASE/session/revoke"

    /** Lists the caller's own devices. */
    public const val SESSIONS: String = "$BASE/session/list"

    // -- group --------------------------------------------------------------

    /** The group's members, roles and permission settings. */
    public const val GROUP: String = "$BASE/group"

    /** Submits queued events. The one write endpoint the offline queue drains into. */
    public const val EVENTS: String = "$BASE/events"

    /** Events since a sequence number, for a client that has been away. */
    public const val EVENTS_SINCE: String = "$BASE/events/since"

    /** A display-ready SkyBlock profile, fetched with the server's Hypixel application key. */
    public const val SKYBLOCK_PROFILE: String = "$BASE/skyblock/profile"

    // -- realtime -----------------------------------------------------------

    /** The WebSocket. Authenticated by an access token in the query, see the auth notes. */
    public const val REALTIME: String = "/realtime"

    /**
     * Pending pairings, for whoever is approving them.
     *
     * Operator-authenticated, like approving itself. The list carries no secrets — a code is worthless
     * without the device secret the mod holds, which is the whole reason the pairing flow has two values
     * instead of one.
     */
    public const val PAIR_PENDING: String = "$BASE/pair/pending"

    /** The accounts a device can be bound to. Operator-authenticated. */
    public const val ACCOUNTS: String = "$BASE/accounts"

    /** The setup page. Plain HTML, served by the same server, so a fresh install needs nothing else. */
    public const val ADMIN: String = "/setup"

    /** Starts the Discord sign-in. A browser path, not an API one — it answers with a redirect. */
    public const val DISCORD_START: String = "/auth/discord"

    /** Where Discord sends the browser back. Registered with the Discord application verbatim. */
    public const val DISCORD_CALLBACK: String = "/auth/discord/callback"

    /** Ends a browser session. */
    public const val WEB_LOGOUT: String = "/auth/logout"

    /** Who the browser is signed in as, and what the server can do. Drives the setup page. */
    public const val WEB_ME: String = "$BASE/me"
}
